name: Update Cydia repo

on:
  push:
    paths:
      - "repo/debs/**"

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages
        run: |
          cd repo
          dpkg-scanpackages -m debs /dev/null > Packages
          bzip2 -f -k Packages

      - name: Generate debs index.html
        run: |
          cd repo/debs

          echo '<!DOCTYPE html>' > index.html
          echo '<html><head><meta charset="utf-8">' >> index.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
          echo '<title>Deb packages</title>' >> index.html
          echo '<link rel="stylesheet" href="../style.css">' >> index.html
          echo '</head><body><div class="container">' >> index.html
          echo '<h1>Available .deb packages</h1><ul>' >> index.html

          for f in *.deb; do
            size=$(du -h "$f" | cut -f1)
            echo "<li><a href=\"$f\">$f</a> ($size)</li>" >> index.html
          done

          echo '</ul></div></body></html>' >> index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo/Packages repo/Packages.bz2 repo/debs/index.html
          git commit -m "Update repo metadata" || exit 0
          git push origin main
