name: Update Cydia Packages

on:
  push:
    paths:
      - "repo/debs/**"

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages
        run: |
          cd repo
          dpkg-scanpackages -m debs /dev/null > Packages
          bzip2 -f -k Packages

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo/Packages repo/Packages.bz2
          git commit -m "Update Packages" || exit 0
          git push origin main
